import re

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from pathlib import Path
from datetime import datetime


REPORT_DIR = Path("reports")

REPORT_DIR.mkdir(
    exist_ok=True
)


def generate_pdf_report(
    question,
    answer,
    sources
):
    question = question.strip()

    # ==========================
# Clean LLM Output
# ==========================

    answer = (
        answer
        .replace("’", "'")
        .replace("‘", "'")
        .replace("“", '"')
        .replace("”", '"')
        .replace("-", "-")  
        .replace("–", "-")   
        .replace("—", "-")   
        .replace("•", "-")
        .replace("■", "-")
        .replace("**", "")
    )

    answer = re.sub(
        r"[\u2010-\u2015\u2212]",
        "-",
        answer
)

    answer = re.sub(
        r"^\s*#+\s*",
        "",
        answer,
        flags=re.MULTILINE
    )

    # ==========================
    # Generate Filename
    # ==========================

    safe_question = question.lower()

    safe_question = re.sub(
        r'[\\/*?:"<>|\r\n]',
        '',
        safe_question
    )

    safe_question = safe_question.replace(
        " ",
        "_"
    )

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    filename = (
        REPORT_DIR
        / f"{safe_question[:40]}_{timestamp}.pdf"
    )

    # ==========================
    # PDF Setup
    # ==========================

    doc = SimpleDocTemplate(
        str(filename)
    )

    styles = getSampleStyleSheet()

    content = []

    # ==========================
    # Title
    # ==========================

    content.append(
        Paragraph(
            "Enterprise Financial Risk Intelligence Report",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    # ==========================
    # Generated Date
    # ==========================

    content.append(
        Paragraph(
            (
                "<b>Generated:</b> "
                f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
            ),
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    # ==========================
    # Company
    # ==========================

    company = (
        sources[0]["company"].upper()
        if sources
        else "UNKNOWN"
    )

    content.append(
        Paragraph(
            f"<b>Company:</b> {company}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    # ==========================
    # Question
    # ==========================

    content.append(
        Paragraph(
            f"<b>Question:</b> {question}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 18)
    )

# ==========================
# Analysis
# ==========================

    content.append(
        Paragraph(
            "Analysis",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 6)
    )

    content.append(
        Paragraph(
            answer.replace(
                "\n",
                "<br/>"
            ),
            styles["BodyText"]
        )
    )


# ==========================
# Footer
# ==========================

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            (
                "Report Generated By: "
                "Financial Risk Intelligence Platform"
            ),
            styles["Italic"]
        )
    )


    # ==========================
    # Sources Page
    # ==========================

    content.append(
        PageBreak()
    )

    content.append(
        Paragraph(
            "Sources Used",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    for i, source in enumerate(
        sources,
        start=1
    ):

        content.append(
            Paragraph(
                (
                    f"<b>Source {i}</b><br/>"
                    f"Company: {source['company']}<br/>"
                    f"Document: {source['document']}<br/>"
                    f"Chunk ID: {source['chunk_id']}"
                ),
                styles["BodyText"]
            )
        )

        content.append(
            Spacer(1, 8)
        )

    doc.build(content)

    return str(filename)